status = [
           "Linux",
           "macOS-x86_64",
           "macOS-arm64",
           "Windows",
         ]
block-labels = [ "no-merge" ]
committer.name = "Multipass CI Bot"
committer.email = "multipass-ci-bot@canonical.com"
timeout-sec = 3600
delete-merged-branches = true
update_base_for_deletes = true
cut_body_after = "---"
